name: Publish HttpSnippet Packages

on:
  push:
    branches:
      - sahar/cicd
    paths-ignore:
      - "package.json"
      - "**.md"

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tag"

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: "https://npm.pkg.github.com"
          scope: "@rapidapi"

      - name: Install root dependencies
        run: yarn --no-progress --non-interactive --frozen-lockfile

      - name: Checkout GitHub Actions
        uses: actions/checkout@v2
        with:
          repository: RapidAPI/rapidapi-github-actions
          ref: master
          token: ${{ secrets.ACTIONS_ACCESS_KEY }}
          path: .github/actions

      - name: Create GitHub Release
        uses: ./.github/actions/create-github-release
        with:
          github_head_ref: ${{ (github.head_ref) }}
          github_base_ref: ${{ (github.base_ref) }}
          ACTIONS_ACCESS_KEY: ${{ (secrets.ACTIONS_ACCESS_KEY) }}

      - name: Publish Package
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.ACTIONS_ACCESS_KEY}}
